#The filter specifies the things we want to remove from the chat.
#You may use multiple filters by typing:
#filter:
# - "ยง[0-9a-f]" # Filter colours
# - "ยงk" # Filter the "funky" text
#
#Note: all filters are case-insensitive
filter: "ยง." # Filter all colours and weird characters