#The filter specifies the things we want to remove from the chat.
#You may use multiple filters by typing:
#filter:
# - "ยง[0-9a-f]" # Filter colours
# - "ยง[^0-9a-f]" # Filter any weird non-colour characters
#
#Note: all filters are case-insensitive
filter: "ยง." # Filter all colours and weird characters

#The mode option specifies how the event should be handled:
# 0: The plugin tries to be the first to process the chat message, then filters it.
# 1: Same as above, but cancels the event and resends the filtered message.
#
# Note: mode 0 does not work for commands.
mode: 1